# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply indicators 
#' @param df A data DataFrame
#' @return A NumericVector
#' @export
multiplyIndicatorsCpp <- function(df) {
    .Call(`_modsem_multiplyIndicatorsCpp`, df)
}

