name: Tests (Ubuntu-latest)

on:
  push:
    branches:
      - main
      - test-workflow
  pull_request:
    branches:
      - main
      - test-workflow

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/kss2k/container-modsem:latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          Rscript -e 'devtools::test(stop_on_failure = TRUE)'
